language: java

install: ./gradlew setupCIWorkspace -S
script:
 - ./gradlew build -S
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

after_success:
 - ./gradlew curse -S
 - export LATEST_JAR="`ls -t build/libs/*.jar | head -1`"
 - export TARGET_NAME="`basename $LATEST_JAR`"
 - curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh && chmod +x dropbox_uploader.sh
 - touch fake-config && ./dropbox_uploader.sh -f fake-config upload $LATEST_JAR $TARGET_NAME

env:
  global:
    TERM=dumb

sudo: false

cache:
  directories:
    - ./libs
    - $HOME/.gradle/caches
