language: java

install: ./gradlew setupCIWorkspace -S
script:
 - ./gradlew build -S
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

after_success: ./gradlew curse -S

env:
  global:
    TERM=dumb

sudo: false

cache:
  directories:
    - ./libs
    - $HOME/.gradle/caches
